import 'package:signup/model/shop.dart';

List<Shops> dataShops = [
  Shops(
    name: 'HIJAB BOUTIQUE',
    category: 'Women Fashion',
    branches: ['mahtt el raml', 'smouha', 'stanley'],
    rating: 4.3,
    image: 'assets/images/kfc2.png',
  ),
  Shops(
    name: 'TREE',
    category: 'Men Fashion',
    branches: ['mahtt el raml', 'smouha', 'stanley'],
    rating: 4.7,
    image: 'assets/images/kfc.png',
  ),
  Shops(
    name: 'Dejav',
    category: 'Footwear',
    branches: ['mahtt el raml', 'smouha', 'siof'],
    rating: 4.0,
    image: 'assets/images/kfc.png',
  ),
  Shops(
    name: 'H&M',
    category: 'Children',
    branches: ['bahary', 'manshia', 'sidi beshr'],
    rating: 2.5,
    image: 'assets/images/kfc.png',
  ),
  Shops(
    name: 'El Moghany',
    category: 'Children',
    branches: ['sidi gaber', 'bahary', 'saba basha'],
    rating: 4.3,
    image: 'assets/images/kfc.png',
  ),
  Shops(
    name: 'Gusto',
    category: 'Children',
    branches: ['sporting', 'gleem', 'stanley'],
    rating: 4.6,
    image: 'assets/images/kfc.png',
  ),
  Shops(
    name: 'Bumble Bee',
    category: 'Children',
    branches: ['manshia', 'smouha', 'miami'],
    rating: 4.1,
    image: 'assets/images/kfc.png',
  ),
  Shops(
    name: 'Junior',
    category: 'Children',
    branches: ['mahtt el raml', 'smouha', 'stanley'],
    rating: 4.5,
    image: 'assets/images/kfc.png',
  ),
  Shops(
    name: 'Chic Trends',
    category: 'Men Fashion',
    branches: ['saba basha', 'mahtt el raml', 'sidi gaber'],
    rating: 4.1,
    image: 'assets/images/chic_trends.png',
  ),
  Shops(
    name: 'Urban Dapper',
    category: 'Women Fashion',
    branches: ['stanley', 'miami', 'bahary'],
    rating: 4.4,
    image: 'assets/images/urban_dapper.png',
  ),
  Shops(
    name: 'Tiny Tots',
    category: 'Children',
    branches: ['manshia', 'siof', 'smouha'],
    rating: 3.9,
    image: 'assets/images/tiny_tots.png',
  ),
  Shops(
    name: 'Active Lifestyle',
    category: 'Activewear',
    branches: ['sporting', 'falaky', 'mahtt el raml'],
    rating: 4.6,
    image: 'assets/images/active_lifestyle.png',
  ),
  Shops(
    name: 'Elegant Threads',
    category: 'Women Fashion',
    branches: ['bahary', 'sidi beshr', 'sidi gaber'],
    rating: 4.2,
    image: 'assets/images/elegant_threads.png',
  ),
  Shops(
    name: 'Sneaker Haven',
    category: 'Footwear',
    branches: ['smouha', 'gleem', 'miami'],
    rating: 4.3,
    image: 'assets/images/sneaker_haven.png',
  ),
  Shops(
    name: 'Young Fashionistas',
    category: 'Men Fashion',
    branches: ['saba basha', 'stanley', 'sidi gaber'],
    rating: 3.8,
    image: 'assets/images/young_fashionistas.png',
  ),
  Shops(
    name: 'Denim Delight',
    category: 'Men Fashion',
    branches: ['mahtt el raml', 'falaky', 'siof'],
    rating: 4.0,
    image: 'assets/images/denim_delight.png',
  ),
  Shops(
    name: 'Trendy Tykes',
    category: 'Children',
    branches: ['manshia', 'sidi beshr', 'mahtt el raml'],
    rating: 4.2,
    image: 'assets/images/trendy_tykes.png',
  ),
  Shops(
    name: 'Sartorial Splendor',
    category: 'Women Fashion',
    branches: ['gleem', 'sidi gaber', 'sporting'],
    rating: 4.8,
    image: 'assets/images/sartorial_splendor.png',
  ),
];
